# ansible-playbook -i /root/.ansible/hosts mysql.yml
---
- hosts: test03
  connection: ssh
  become: yes
  become_user: root
  vars:
    - testvar: test mysql
#  roles:
#    - role: geerlingguy.mysql
  pre_tasks:
    - name: test pre tasks
      debug:
        msg: "test pre tasks modul....."

  roles:
    - role: localRepo
    - role: mysql
      vars:
        mysql_version: 5.7.25
#        mysql_root_password_update: True
        mysql_character_set_server: utf8
        mysql_collation_server: utf8_bin
        mysql_mysql_default_character_set: utf8
        mysql_client_default_character_set: utf8

        mysql_databases:
          - name: kcc
            encoding: utf8
            collation: utf8_bin

        mysql_users:
          - name: kcc
            host: "%"
            password: "Mp@3965122"
            priv: "kcc.*:ALL"

...