# ansible-playbook -i /root/.ansible/hosts mysql.yml
---
- hosts: test03
  connection: ssh
  become: yes
  become_user: root
  vars:
    yum_host: yum.marcpoint.com
    mysql_version: "5.6.15"

  tasks:
    - name: init python evn
      command: "ls ./"
      args:
        chdir: "/home"
        creates: "./soft"
...