# ansible-playbook -i /root/.ansible/hosts mysql.yml
---
- hosts: test03
  connection: ssh
  become: yes
  become_user: root
  vars:
    yum_host: yum.marcpoint.com
    mysql_version: "5.6.15"

  tasks:
    - name: test version
      set_fact:
        "{{ item.key }}": "{{ item.value}}"
      with_dict: "{{ __mysql_version_diff['.'.join(mysql_version.split('.')[:2])] }}"

    - name: debug
      debug:
        var: mysql_packages
...