# ansible-playbook -i /Users/guoyuanpei/workspace/pworkspace/ansible/hosts /Users/guoyuanpei/workspace/pworkspace/ansible/playbook/test.yml
---
- hosts: test03
  connection: ssh
  become: yes
  become_user: root
  vars:
    - testvar: test mysql
    - pub_key: ""

  tasks:
    # openssh_keypair has a bug bugs, if key already exists and needs to be deleted first。 Modify the source code
    - name: generate pubilc key
      openssh_keypair:
        path: ~/.ssh/id_rsa
        type: rsa
        force: False
        state: present
      register: ssh_key

    - name: get public_key
      debug:
        msg: "{{ ssh_key.public_key }}"

#    - name: debug gogs_deploy_key.py
#      gogs_deploy_key:
#        domain: "git.marcpoint.com"
#        api_username: "yuanpei.guo"
#        api_password: "Mp3965122"
#        project: "server/brand_health"
#        title: "test1"
#        key: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA9vAXOR1Qsaot6sZCQ65KJMxXjOAoqjl6ET+XNb4l6ANd9A/gIoHo0BzWj+Pvoc2v80OpIMIfk/tE5ujSN74ii6Ur/VHRgL7KpA11rYmmXon59QcwlEnY65VaTbJbAalb71fvszLayIMC5GGmUwsUaj0fQ+/aJb0jkk8VPKdzPZ3oHnu1vkvvI1nq1XfwCWFQA+HRx3Sgy8drNMmjub/nKAlR9JHqTOzMM5mW39rZWs3LA4XQRAJz20+/hJo07lUGu6EDJBZZAdsznnjTC8lKjxGGTq2CjVRewigQVHzxKv10zuJHmeVgHQkyq5I5FOB5MrS7I4TYK6mpvCD4YW+kZQ== root@virt03"
#        state: "present"
#      delegate_to: 127.0.0.1
...