# ansible-playbook -i /Users/guoyuanpei/workspace/pworkspace/ansible/hosts /Users/guoyuanpei/workspace/pworkspace/ansible/playbook/test.yml
---
- hosts: test03
  connection: ssh
  become: yes
  become_user: root
  vars:
    - testvar: test mysql
    - pub_key: ""

  tasks:
    # openssh_keypair has a bug bugs, if key already exists and needs to be deleted first。 Modify the source code
    - name: generate pubilc key
      openssh_keypair:
        path: ~/.ssh/id_rsa
        type: rsa
        force: False
        state: present
        size: 2048
      register: ssh_keygen

    - name: get public_key
      debug:
        msg: "{{ ssh_keygen.public_key }}"

...