# ansible-playbook -i /Users/guoyuanpei/workspace/pworkspace/ansible/hosts /Users/guoyuanpei/workspace/pworkspace/ansible/playbook/test.yml
---
- hosts: test03
  connection: ssh
  become: yes
  become_user: root
  vars:
    yum_host: yum.marcpoint.com
    mysql_version: "5.6.15"

  tasks:
    - name: see if the specified user exists
      getent:
        database: passwd
        key: "root"
        fail_key: no

    - name: debug getent info
      debug:
        var: getent_passwd
...