---
- name: Ensure MySQL databases are present.
  mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    state: "{{ item.state | default('present') }}"
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
  with_items: "{{ mysql_databases }}"
