---

__mysql_version_diff:
  "5.5":
    mysql_packages:
      - MySQL-client
      - MySQL-server
      - MySQL-devel
      - MySQL-shared*
    mysql_daemon: mysql
    sql_mode: NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES

  "5.6":
    mysql_packages:
      - MySQL-client
      - MySQL-server
      - MySQL-devel
      - MySQL-shared*
    mysql_daemon: mysql

  "5.7":
    mysql_packages:
      - mariadb
      - mariadb-server
      - mariadb-libs
      - perl-DBD-MySQL
    mysql_daemon: mariadb

  "8.0":
    mysql_packages:
      - mariadb
      - mariadb-server
      - mariadb-libs
      - perl-DBD-MySQL
    mysql_daemon: mariadb
    mysql_default_authentication_plugin: mysql_native_password

__mysql_slow_query_log_file: /var/log/mysql-slow.log
__mysql_log_error: /var/log/mariadb/mariadb.log
__mysql_syslog_tag: mariadb
__mysql_pid_file: /var/run/mariadb/mariadb.pid
__mysql_config_file: /etc/my.cnf
__mysql_config_include_dir: /etc/my.cnf.d
__mysql_socket: /var/lib/mysql/mysql.sock
__mysql_supports_innodb_large_prefix: true
